name: Respond to Contract Verification Event
on:
  repository_dispatch:
    types:
      - contract_requiring_verification_published
permissions:
  contents: write
jobs:
  respond_to_event:
    runs-on: ubuntu-latest
    steps:
      - name: Echo success message
        run: echo "SUCCESS - TRIGGER received - contract_requiring_verification_published"
